apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8080
    - name: 8181-tcp
      port: 8181
      targetPort: 8181
  selector:
    io.kompose.service: api-gateway
