apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: inventory-service
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventory-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/microservices-parent-updated-default: "true"
        io.kompose.service: inventory-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-inventory:3306/inventory_service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: beko2001/inventory-service:latest
          name: inventory-service
      restartPolicy: Always
