apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/microservices-parent-updated-default: "true"
        io.kompose.service: keycloak
    spec:
      volumes:
        - name: realms-git-volume
          emptyDir: {}
      initContainers:
        - name: clone-repo
          image: alpine/git
          command: ["sh", "-c", "git clone https://github.com/Berko01/KeycloakConfig.git /data"]
          volumeMounts:
            - name: realms-git-volume
              mountPath: /data
      containers:
        - name: keycloak
          args:
            - start-dev
            - --import-realm
          env:
            - name: DB_ADDR
              value: mysql
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: password
            - name: DB_VENDOR
              value: MYSQL
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak:23.0.5
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realms-git-volume
              mountPath: /opt/keycloak/data/import
