apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mysql-order
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-order
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/microservices-parent-updated-default: "true"
        io.kompose.service: mysql-order
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: order_service
            - name: MYSQL_PASSWORD
              value: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: mysql_user
          image: mysql:latest
          name: mysql-order
          ports:
            - containerPort: 3306
              hostPort: 3308
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-order-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-order-claim0
          persistentVolumeClaim:
            claimName: mysql-order-claim0
